#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ribozyme_reaction_coordinate_quotient.py — deterministic stdlib-only
verification of the G26-RB-2 branch-lock: the J₂=24 invariant for the
RIBOZYME axis is realized as the symmetry group of the 4-state catalytic
reaction-coordinate ladder.

BRANCH-LOCK DECISION (G26-RB-2, locked 2026-05-12, owner: hexa-bio session):

  The ribozyme "reaction-coordinate quotient" group is the full permutation
  group  S₄  of the 4 directed catalytic states

      0  substrate_bound
      1  transition_state
      2  cleaved_intermediate
      3  product_released

  with  |S₄| = 4! = 24 = J₂ .  S₄ is isomorphic to the rotational
  octahedral group  O  (the chiral cube/octahedron symmetry, |O| = 24),
  realized concretely here as the action of O on the 4 body-diagonals of a
  cube — this is the bridge to the *geometric* J₂=24 already used by the
  WEAVE / VIROCAPSID axes (σ(6)=12 cuboctahedron / icosahedron vertex sets,
  octahedral O ⊂ icosahedral-context).  The *physical* reaction trajectory
  is the unique strictly-monotone Hamiltonian path 0→1→2→3 through the
  ladder; the group acts simply transitively (regularly) on the 24 total
  orderings of the 4 states, so the trajectory's orbit has size 24 = J₂.

  Equivalently and most economically:
      J₂  =  |Aut( 4-state catalytic ladder, as an unordered set )|  =  4!  =  24
  consistent with the master identity  σ·φ = n·τ = J₂ , i.e. 12·2 = 6·4 = 24.

  Revisability (raw#10 honest C3 / §A.1 caveat): this is the n=6-lattice
  *projection* for the ribozyme axis — STRUCTURAL-EXACT-CANDIDATE.  The
  group-order arithmetic (4! = |O| = 24) is a deductive certainty; the
  *interpretive choice* (that the relevant group is S₄ acting on the
  catalytic ladder, rather than some other order-24 structure) is the
  branch-lock and may be superseded if a stronger reaction-mechanism-derived
  interpretation emerges.  Lock = freeze the working interpretation, not a
  claim of mechanistic uniqueness.

This module verifies the deductive content of the lock: |S₄| = 24, the
group axioms, the explicit O-on-cube-diagonals realization (|O| = 24 and
⟨O generators⟩ = S₄), regular action on the 24 orderings, and master-identity
consistency.  Pure stdlib, no network/time/random/env → byte-identical
re-runs (§11 deductive verification contract).
"""

from __future__ import annotations
from itertools import permutations
from typing import Dict, FrozenSet, List, Tuple
import sys

# ── n=6 lattice constants (shared with .roadmap.hexa_bio §A.1) ──
N6, SIGMA, TAU, PHI, J2 = 6, 12, 4, 2, 24

# ── the 4 directed catalytic states (the reaction-coordinate ladder) ──
STATES: List[str] = [
    "substrate_bound",       # 0
    "transition_state",      # 1
    "cleaved_intermediate",  # 2
    "product_released",      # 3
]
NSTATES = len(STATES)  # == 4 == TAU


# ── permutation-group plumbing (permutations as tuples p with p[i] = image of i) ──

def identity(n: int) -> Tuple[int, ...]:
    return tuple(range(n))


def compose(p: Tuple[int, ...], q: Tuple[int, ...]) -> Tuple[int, ...]:
    """(p∘q)[i] = p[q[i]] — apply q first, then p."""
    return tuple(p[q[i]] for i in range(len(q)))


def inverse(p: Tuple[int, ...]) -> Tuple[int, ...]:
    inv = [0] * len(p)
    for i, pi in enumerate(p):
        inv[pi] = i
    return tuple(inv)


def order_of(p: Tuple[int, ...]) -> int:
    n = len(p)
    e, cur, k = identity(n), p, 1
    while cur != e:
        cur = compose(p, cur)
        k += 1
    return k


def closure(generators: List[Tuple[int, ...]]) -> FrozenSet[Tuple[int, ...]]:
    """Subgroup generated by `generators` (BFS over composition; finite group)."""
    n = len(generators[0])
    seen = {identity(n)}
    frontier = [identity(n)]
    while frontier:
        nxt = []
        for g in frontier:
            for h in generators:
                for cand in (compose(g, h), compose(h, g)):
                    if cand not in seen:
                        seen.add(cand)
                        nxt.append(cand)
        frontier = nxt
    return frozenset(seen)


def is_group(elems: FrozenSet[Tuple[int, ...]]) -> bool:
    n = len(next(iter(elems)))
    if identity(n) not in elems:
        return False
    for g in elems:
        if inverse(g) not in elems:
            return False
        for h in elems:
            if compose(g, h) not in elems:
                return False
    return True  # associativity is automatic for function composition


# ── the rotational octahedral group O, on the 4 cube body-diagonals ──
# Cube body-diagonals, indexed by the vertex representative with x = +1:
#   d0 = (+,+,+)   d1 = (+,+,-)   d2 = (+,-,+)   d3 = (+,-,-)
_DIAG_REP = [(1, 1, 1), (1, 1, -1), (1, -1, 1), (1, -1, -1)]
_DIAG_INDEX = {v: i for i, v in enumerate(_DIAG_REP)}


def _normalize(v: Tuple[int, int, int]) -> Tuple[int, int, int]:
    """Pick the body-diagonal representative with x = +1 (flip the whole vector if x = -1)."""
    if v[0] == -1:
        return (-v[0], -v[1], -v[2])
    return v


def _diag_perm(rot) -> Tuple[int, ...]:
    """Turn a rotation rot: R³→R³ (on ±1 vectors) into a permutation of the 4 diagonals."""
    return tuple(_DIAG_INDEX[_normalize(rot(_DIAG_REP[i]))] for i in range(4))


# generator A: 90° rotation about the z-axis  (x,y,z) -> (-y, x, z)   [order 4]
_GEN_A = _diag_perm(lambda v: (-v[1], v[0], v[2]))
# generator B: 120° rotation about body-diagonal d0  (x,y,z) -> (z, x, y)   [order 3]
_GEN_B = _diag_perm(lambda v: (v[2], v[0], v[1]))


# ── self-check ──────────────────────────────────────────────────────────

def _selfcheck() -> int:
    print("ribozyme_reaction_coordinate_quotient — G26-RB-2 branch-lock verification (deductive)")
    print(f"  branch-lock: J₂ = |S₄| = 4! = 24, S₄ ≅ O (rot. octahedral); 4-state catalytic ladder = {STATES}")
    print()
    fails = 0

    def check(label: str, cond: bool, detail: str = "") -> None:
        nonlocal fails
        ok = bool(cond)
        if not ok:
            fails += 1
        print(f"  [{'PASS' if ok else 'FAIL'}] {label}" + (f"  —  {detail}" if detail else ""))

    # 1. the ladder has exactly TAU = 4 states
    check("4-state catalytic ladder cardinality == τ(6) == 4",
          NSTATES == TAU == 4, f"|STATES| = {NSTATES}")

    # 2. |S₄| = 4! = 24
    s4 = frozenset(permutations(range(NSTATES)))
    check("|S₄| = 4! = 24 = J₂",
          len(s4) == 24 == J2, f"|S₄| = {len(s4)}, J₂ = {J2}")

    # 3. S₄ is a group (identity, inverses, closure)
    check("S₄ satisfies group axioms (identity ∈, closed, every elem invertible)",
          is_group(s4))

    # 4. explicit O realization: generators on cube body-diagonals
    check("generator A (90° face rotation) has order 4",
          order_of(_GEN_A) == 4, f"A = {_GEN_A}, ord = {order_of(_GEN_A)}")
    check("generator B (120° body-diagonal rotation) has order 3",
          order_of(_GEN_B) == 3, f"B = {_GEN_B}, ord = {order_of(_GEN_B)}")
    O = closure([_GEN_A, _GEN_B])
    check("|O| = |⟨A, B⟩| = 24 (rotational octahedral group on 4 diagonals)",
          len(O) == 24, f"|O| = {len(O)}")
    check("O = S₄  (i.e. the octahedral rotation group acts as the FULL Sym(4) on the diagonals → O ≅ S₄)",
          O == s4)
    check("O satisfies group axioms",
          is_group(O))

    # 5. regular (simply transitive) action of S₄ on the 24 total orderings of the 4 states
    base = tuple(range(NSTATES))                       # the physical reaction coordinate 0→1→2→3
    orbit = {tuple(g[base[i]] for i in range(NSTATES)) for g in s4}
    stabilizer = [g for g in s4 if tuple(g[base[i]] for i in range(NSTATES)) == base]
    all_orderings = set(permutations(range(NSTATES)))
    check("S₄ orbit of the reaction-coordinate ordering 0→1→2→3 has size 24 = J₂",
          len(orbit) == 24 == J2, f"|orbit| = {len(orbit)}")
    check("the action on orderings is regular: orbit covers all 4! orderings AND stabilizer is trivial",
          orbit == all_orderings and len(stabilizer) == 1,
          f"|orbit| = {len(orbit)}, |stabilizer| = {len(stabilizer)}")
    check("orbit-stabilizer arithmetic: |S₄| = |orbit| · |stab| = 24 · 1 = 24",
          len(s4) == len(orbit) * len(stabilizer) == 24)

    # 6. unique strictly-monotone Hamiltonian path through the ladder (the reaction trajectory)
    monotone = [p for p in permutations(range(NSTATES)) if all(p[i] < p[i + 1] for i in range(NSTATES - 1))]
    check("exactly ONE strictly-increasing total order on the 4 states (the physical reaction coordinate)",
          len(monotone) == 1 and monotone[0] == (0, 1, 2, 3),
          f"monotone orderings = {monotone}")

    # 7. master-identity consistency: 4! = |O| = 24 = σ·φ = n·τ
    check("master identity: 4! = |O| = J₂ = σ·φ = n·τ = 24",
          (24 == len(s4) == len(O) == J2 == SIGMA * PHI == N6 * TAU),
          f"4! = {len(s4)}, |O| = {len(O)}, J₂ = {J2}, σ·φ = {SIGMA*PHI}, n·τ = {N6*TAU}")

    # 8. determinism — re-derive O from scratch, must be byte-identical
    O2 = closure([_diag_perm(lambda v: (-v[1], v[0], v[2])), _diag_perm(lambda v: (v[2], v[0], v[1]))])
    check("determinism — re-derived O equals O (byte-identical permutation set)",
          O2 == O)

    print()
    if fails == 0:
        print("  --- summary --- all checks PASS → verdict: PASS")
        print("  branch-lock G26-RB-2 LOCKED: J₂(ribozyme) = |S₄| = 24, S₄ ≅ O, regular action on the")
        print("  24 catalytic-ladder orderings. Deductive (group-order arithmetic); interpretive choice")
        print("  is the branch-lock — STRUCTURAL-EXACT-CANDIDATE per §A.1, revisable if a stronger")
        print("  mechanism-derived order-24 structure is identified.")
        print("__RIBOZYME_REACTION_COORDINATE_QUOTIENT__ PASS")
        return 0
    print(f"  --- summary --- {fails} FAIL → verdict: FAIL")
    print("__RIBOZYME_REACTION_COORDINATE_QUOTIENT__ FAIL")
    return 1


if __name__ == "__main__":
    sys.exit(_selfcheck())
